version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:16.0-alpine3.18
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: ./questioner
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
      